name: time-series-backend

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: backend-app
    volumes:
      - /app/node_modules
    ports:
      - 13000:3000
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASS: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}

volumes:
  pgdata: