###

GET http://localhost:13000/api

###
GET http://localhost:13000/

###
GET http://localhost:13000/metadata

###
POST http://localhost:3000/api/products 
Content-Type: application/json

{
    "product_name": "NovoProduto",
    "quantity": 10,
    "price": 10.25
}

###
GET http://localhost:13000/metadata/SCN10_VAITP10

###
GET http://localhost:13000/time-series/SCN10_VAITP10

###
GET http://localhost:13000/time-series/DINVESTE

###
GET http://localhost:13000/schema/DINVESTE

###
GET http://localhost:13000/api